In [27]:
import numpy as np
import scipy

In [34]:
a = np.array(range(1,101), dtype=np.int)
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [35]:
b = np.array(range(1,100,2), dtype=np.int)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


In [48]:
c = np.array([np.pi * f * 0.01 for f in range(-100,101)], dtype=np.float64)
print(c)

[-3.14159265 -3.11017673 -3.0787608  -3.04734487 -3.01592895 -2.98451302
 -2.95309709 -2.92168117 -2.89026524 -2.85884931 -2.82743339 -2.79601746
 -2.76460154 -2.73318561 -2.70176968 -2.67035376 -2.63893783 -2.6075219
 -2.57610598 -2.54469005 -2.51327412 -2.4818582  -2.45044227 -2.41902634
 -2.38761042 -2.35619449 -2.32477856 -2.29336264 -2.26194671 -2.23053078
 -2.19911486 -2.16769893 -2.136283   -2.10486708 -2.07345115 -2.04203522
 -2.0106193  -1.97920337 -1.94778745 -1.91637152 -1.88495559 -1.85353967
 -1.82212374 -1.79070781 -1.75929189 -1.72787596 -1.69646003 -1.66504411
 -1.63362818 -1.60221225 -1.57079633 -1.5393804  -1.50796447 -1.47654855
 -1.44513262 -1.41371669 -1.38230077 -1.35088484 -1.31946891 -1.28805299
 -1.25663706 -1.22522113 -1.19380521 -1.16238928 -1.13097336 -1.09955743
 -1.0681415  -1.03672558 -1.00530965 -0.97389372 -0.9424778  -0.91106187
 -0.87964594 -0.84823002 -0.81681409 -0.78539816 -0.75398224 -0.72256631
 -0.69115038 -0.65973446 -0.62831853 -0.5969026  -0.

In [49]:
d = np.array([np.pi * f * 0.01 for f in range(-100,101) if f != 0], dtype=np.float64)
print(d)

[-3.14159265 -3.11017673 -3.0787608  -3.04734487 -3.01592895 -2.98451302
 -2.95309709 -2.92168117 -2.89026524 -2.85884931 -2.82743339 -2.79601746
 -2.76460154 -2.73318561 -2.70176968 -2.67035376 -2.63893783 -2.6075219
 -2.57610598 -2.54469005 -2.51327412 -2.4818582  -2.45044227 -2.41902634
 -2.38761042 -2.35619449 -2.32477856 -2.29336264 -2.26194671 -2.23053078
 -2.19911486 -2.16769893 -2.136283   -2.10486708 -2.07345115 -2.04203522
 -2.0106193  -1.97920337 -1.94778745 -1.91637152 -1.88495559 -1.85353967
 -1.82212374 -1.79070781 -1.75929189 -1.72787596 -1.69646003 -1.66504411
 -1.63362818 -1.60221225 -1.57079633 -1.5393804  -1.50796447 -1.47654855
 -1.44513262 -1.41371669 -1.38230077 -1.35088484 -1.31946891 -1.28805299
 -1.25663706 -1.22522113 -1.19380521 -1.16238928 -1.13097336 -1.09955743
 -1.0681415  -1.03672558 -1.00530965 -0.97389372 -0.9424778  -0.91106187
 -0.87964594 -0.84823002 -0.81681409 -0.78539816 -0.75398224 -0.72256631
 -0.69115038 -0.65973446 -0.62831853 -0.5969026  -0.

In [32]:
e = np.array([max(np.sin(i), 0.0) for i in range(1,101)], dtype=np.float64)
print(e)

[ 0.84147098  0.90929743  0.14112001  0.          0.          0.          0.6569866
  0.98935825  0.41211849  0.          0.          0.          0.42016704
  0.99060736  0.65028784  0.          0.          0.          0.14987721
  0.91294525  0.83665564  0.          0.          0.          0.
  0.76255845  0.95637593  0.27090579  0.          0.          0.
  0.55142668  0.99991186  0.52908269  0.          0.          0.
  0.29636858  0.96379539  0.74511316  0.          0.          0.
  0.01770193  0.85090352  0.90178835  0.12357312  0.          0.          0.
  0.67022918  0.98662759  0.39592515  0.          0.          0.
  0.43616476  0.99287265  0.63673801  0.          0.          0.          0.1673557
  0.92002604  0.82682868  0.          0.          0.          0.
  0.77389068  0.95105465  0.25382336  0.          0.          0.
  0.56610764  0.99952016  0.51397846  0.          0.          0.
  0.31322878  0.96836446  0.73319032  0.          0.          0.          0.0353983
  0.8

In [38]:
A = np.array(range(1,101), dtype=np.int).reshape((10,10))
print(A)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [40]:
B = np.diag(range(1,101)) + np.diag(range(99,0,-1),k=1) + np.diag(range(99,0,-1),k=-1)
print(B)

[[  1  99   0 ...,   0   0   0]
 [ 99   2  98 ...,   0   0   0]
 [  0  98   3 ...,   0   0   0]
 ..., 
 [  0   0   0 ...,  98   2   0]
 [  0   0   0 ...,   2  99   1]
 [  0   0   0 ...,   0   1 100]]


In [41]:
C = np.array([[1 if i <= j else 0 for j in range(1,101)] for i in range(1,101)], dtype=np.int)
print(C)

[[1 1 1 ..., 1 1 1]
 [0 1 1 ..., 1 1 1]
 [0 0 1 ..., 1 1 1]
 ..., 
 [0 0 0 ..., 1 1 1]
 [0 0 0 ..., 0 1 1]
 [0 0 0 ..., 0 0 1]]


In [46]:
D = np.array([range(1,101), [np.math.factorial(i) for i in range(1,101)]])
print(D)

[[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
  28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51
  52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
  76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99
  100]
 [1 2 6 24 120 720 5040 40320 362880 3628800 39916800 479001600 6227020800
  87178291200 1307674368000 20922789888000 355687428096000 6402373705728000
  121645100408832000 2432902008176640000 51090942171709440000
  1124000727777607680000 25852016738884976640000 620448401733239439360000
  15511210043330985984000000 403291461126605635584000000
  10888869450418352160768000000 304888344611713860501504000000
  8841761993739701954543616000000 265252859812191058636308480000000
  8222838654177922817725562880000000 263130836933693530167218012160000000
  8683317618811886495518194401280000000
  295232799039604140847618609643520000000
  10333147966386144929666651337523200000000
  37199332678990121746

In [47]:
E = np.array([[1 if j % i == 0 else 0 for j in range(1,101)] for i in range(1,101)])
print(E)

[[1 1 1 ..., 1 1 1]
 [0 1 0 ..., 1 0 1]
 [0 0 1 ..., 0 1 0]
 ..., 
 [0 0 0 ..., 1 0 0]
 [0 0 0 ..., 0 1 0]
 [0 0 0 ..., 0 0 1]]
